# Generated by Django 2.1.7 on 2019-03-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('信息科学与技术学院', '信息科学与技术学院'), ('化学工程学院', '化学工程学院'), ('材料科学与工程学院', '材料科学与工程学院'), ('机电工程学院', '机电工程学院'), ('经济管理学院', '经济管理学院'), ('理学院', '理学院'), ('文法学院', '文法学院'), ('生命科学与技术学院', '生命科学与技术学院'), ('继续教育学院', '继续教育学院'), ('马克思主义学院', '马克思主义学院'), ('国际教育学院', '国际教育学院'), ('侯德榜工程师学院', '侯德榜工程师学院'), ('能源学院', '能源学院'), ('巴黎居里工程师学院', '巴黎居里工程师学院')], default='BUCT', max_length=32, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('grant', models.CharField(default='3', max_length=32)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('start_year', models.CharField(default='2019', max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Dept')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
