# Generated by Django 2.1.7 on 2019-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_year',
            field=models.CharField(default='2023', max_length=32),
        ),
    ]
